# Site settings
course_name: Basic Programming Autumn 1403
course_description: "Welcome to the Basic Programming course of Department of Mathematical Sciences Sharif University of Technology."
course_semester: "Autumn 2024"

baseurl: "/Basic-Programming-Autumn-03" # the subpath of your site, e.g. /blog/
url: "http://theblackdemon.github.io/" # the base hostname & protocol for your site

schoolname: "Sharif University of Technology"
schoolurl: "https://sharif.edu"
twitter_username: null

address: |
    Tehran 
    Iran

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
